### ISSUE TITLE
Use google tag manager to track outbound clicks and video views

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind-docs#10]
We use google tag manager for tracking events.

Currently, the outbound clicks aren't tracked in a very organized way. The event category and event action is just the URL. However, I think the event category should be "Outbound click" and the action is the URL.

In addition, we have not hooked into the video player yet, an event needs to be added to track the playing of the video.

**Comment by laven26** [comment]
I can look into it

**Comment by sishida** [comment]
Update:
- Laven set up the tracking of the video.
- I will try to learn more about Google tag manager in between other work items.

**Comment by sghung** [comment]
No additional work required, google tag manager was setup
