### ISSUE TITLE
Adding documentation for OpenAPI

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind-docs#108]
We need to add Codewind OpenAPI tools docs to the landing pages table of contents. Currently the table of contents links out to the OpenAPI repositories.

Eclipse: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/codewind-openapi-eclipse.md
VS Code: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/codewind-openapi-vscode.md

**Comment by micgibso** [comment]
@sishida Is this finished, can it be closed? Thanks

**Comment by sishida** [comment]
Links to OpenAPI content on the Codewind landing pages:
1. https://www.eclipse.org/codewind/open-api-tools-for-vscode.html
2. https://www.eclipse.org/codewind/open-api-tools-for-eclipse.html
