### ISSUE TITLE
Clarify the pronunciation of Codewind

### ISSUE THREAD

**Issue by cccanderson** [eclipse/codewind-docs#11]
From https://www.eclipse.org/lists/codewind-dev/msg00003.html , we can see that we need to clarify that the pronunciation of Codewind is "wind" like "the wind blows" and not "wind up a top".

We could do this with a pronunciation link, or a link to a YouTube video, or anything... just as long as it is done.

**Comment by deboer-tim** [comment]
Well, I do pronounce it as 'wind blowing' in the intro video. I guess that means they didn't watch it? :)

Not sure if you think we need a separate pronounciation link or just wait and see if others pick up on it.

**Comment by sishida** [comment]
Tim's intro video on the landing pages themselves (https://www.eclipse.org/codewind/) as well as Andy's installation video (https://www.youtube.com/watch?v=qujVACLnbmM) on the Codewind YouTube channel both contain the pronunciation of Codewind. :) 

We've also got issues open to make these videos easier to find:
1️⃣ https://github.ibm.com/dev-ex/design-work/issues/217
2️⃣ https://github.ibm.com/dev-ex/landing-pages/issues/1171

I'm hoping that the videos can suffice as our pronunciation guides, especially as we add more videos and they gain more views. :)

**Comment by sghung** [comment]
Closing since no additional work is required
