### ISSUE TITLE
Enable linking to headings on a page

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind-docs#122]
Create a way to link to headings and subheadings within a page.

For example, this site appears to have a unique URL for its headings, so you can link directly to a specific heading on that page: https://help.github.com/en/articles/securing-your-github-pages-site-with-https

It'd be nice to have the same sort of functionality on our site, as well.

**Comment by micgibso** [comment]
@travis1111 I remember working with you on something similar for Microclimate, is this as easy to implement for Codewind?

**Comment by travis1111** [comment]
this one?
![image](https://user-images.githubusercontent.com/35569780/64971832-44970800-d876-11e9-974d-fd7b78d52269.png)

Sure I can make that happen :-)

**Comment by micgibso** [comment]
Yes, that's the one :) 
Great, thanks, that'll help with our linking no end.

**Comment by micgibso** [comment]
Implemented, thanks @travis1111. 
@sishida Could you please close this as complete? thank you.
