### ISSUE TITLE
Ensure website conforms to Eclipse website rules

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind-docs#17]
For example, we're missing the required footer. Please refer to the guide:

https://www.eclipse.org/projects/handbook/#resources-website and https://www.eclipse.org/projects/handbook/#trademarks-website

**Comment by travis1111** [comment]
![image](https://user-images.githubusercontent.com/35569780/61064043-06d9b700-a3cf-11e9-8c5b-ad81e011c869.png)

**Comment by kimholmes** [comment]
@sghung @travis1111 Here is an updated design for the footer:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/21316329/62393119-4495af80-b537-11e9-8247-8d7577e2d6d6.png">

Sketch file:
https://ibm.box.com/s/06vlf9la8vycn75fyzep2u4a172n662u

HTML/CSS specs:
https://ibm.box.com/s/28chm68cr9eagcmhjfc9wev8tlm1c8mr

FYI - I used the specs at this link:
https://www.eclipse.org/projects/handbook/#trademarks-website

Pls let me know if I've missed anything.

**Comment by sghung** [comment]
Closing since footer was updated to conform to Eclipse website rules
