### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind-docs#19]
Naveen found some broken links in https://www.eclipse.org/codewind/mdt-vsc-tutorial.html.

The following links aren't working:
Open Folder as Workspace
Show Project Overview
Show Application Log
Open in Browser
Restart in Debug Mode
reattach the debugger

These links take you to an Error 404 page.

**Comment by sghung** [comment]
Fixed as part of https://github.com/eclipse/codewind-docs/pull/23
