### ISSUE TITLE
Add openapi docs for OpenAPI Tools

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind-docs#31]
We're still missing the help docs.
https://ibm.ent.box.com/notes/492349926519

Thanks Sarah for editing/reviewing the README.md files here:
https://github.com/eclipse/codewind-openapi-vscode
https://github.com/eclipse/codewind-openapi-eclipse

I think you could start with content from those files.

**Comment by sishida** [comment]
I'll start work on this issue. 👍

**Comment by sishida** [comment]
Incorporated feedback with https://github.com/eclipse/codewind-docs/pull/35.

**Comment by sishida** [comment]
@keithchong Does this issue look good to close, or would you like to add more info to the Open API files? Please let me know. Thanks!

Links to updated docs:
- Eclipse: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/codewind-openapi-eclipse.md
- VS Code: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/codewind-openapi-vscode.md

**Comment by keithchong** [comment]
LGTM
