### ISSUE TITLE
Add Tekton integration

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind-docs#39]
Add Tekton integration to the docs.
- What is it? Why is it important? How does it fit into the overall cloud picture?
- Why do I need it? How does it help deploy my apps into the cloud?

**Comment by micgibso** [comment]
https://github.com/eclipse/codewind/issues/106

**Comment by sishida** [comment]
I'll work on this issue. 👍

**Comment by sishida** [comment]
I worked with Jag to add the link to the file. This issue is good to close. If we want to add more Tekton content, we can open a new issue in the future.

**Comment by elsony** [comment]
Closing as requested above
