### ISSUE TITLE
Accessibility test the docs pages

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind-docs#44]
Use the Dynamic Assessment Plugin (DAP) to test https://www.eclipse.org/codewind/docindex.html

**Comment by micgibso** [comment]
Tested a selection of topics:
https://www.eclipse.org/codewind/docindex.html
https://www.eclipse.org/codewind/mdteclipseoverview.html
https://www.eclipse.org/codewind/mdt-vsc-overview.html
Reports attached.
[accessibility.zip](https://github.com/eclipse/codewind-docs/files/3477144/accessibility.zip)

**Comment by sghung** [comment]
@travis1111 can you take a look? (if so, make a comment so I can add you as an assignee) Thank you

**Comment by travis1111** [comment]
Sure I will

**Comment by micgibso** [comment]
Tested selection of topics on new docs pages, reports attached:
[Accessibility 20-08-2019.zip](https://github.com/eclipse/codewind-docs/files/3520176/Accessibility.20-08-2019.zip)

**Comment by micgibso** [comment]
Zero violations on latest pages, reports attached: 
[Accessibility 23-08-2019.zip](https://github.com/eclipse/codewind-docs/files/3533397/Accessibility.23-08-2019.zip)
