### ISSUE TITLE
Mattermost Icon - link is incorrect

### ISSUE THREAD

**Issue by ericdylanpeters2** [eclipse/codewind-docs#7]
The Mattermost icon on page https://www.eclipse.org/codewind/ should point to https://mattermost.eclipse.org/eclipse/channels/eclipse-codewind (currently points to mailto:codewind-dev@eclipse.org )

**Comment by travis1111** [comment]
Just fixed it.

**Comment by ericdylanpeters2** [comment]
Fixed!
