### ISSUE TITLE
Links to anchors not working

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind-docs#8]
Some of the .md files (like installlocally.md) have a link like this: `[Troubleshooting page](troubleshooting#installing-codewind)` which the .html fix is turning into `https://www.eclipse.org/codewind/troubleshooting#installing-codewind.html`

It should instead convert them to `https://www.eclipse.org/codewind/troubleshooting.html#installing-codewind`

**Comment by sishida** [comment]
@jopit Thanks for raising this issue. :) I'm going to try to create a PR for these edits. Could you please assign this issue to me? I am currently not a committer, so I can't assign myself. Thanks!

**Comment by travis1111** [comment]
@sishida Thanks for fixing this.  When you fix these, do you mind not to hardcode the root url?  Just `troubleshooting.html#installing-codewind`.

thanks

**Comment by sishida** [comment]
@jopit Hi, John, It looks like @travis1111 fixed the URLs. (Thanks, Travis!) This PR appears to covers the link edits: https://github.com/eclipse/codewind-docs/commit/1c81407ed70c8ca7e6db13e506138e11b8683214#diff-24ddf17347be80f4ed833c387dcf4ae8

If these changes are satisfactory to you, could you please close this issue? Thank you! :)
