### ISSUE TITLE
Getting Started shows wrong product icons

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind-docs#88]
![image](https://user-images.githubusercontent.com/8888438/63801154-a26eaa80-c8dd-11e9-8ba5-dbfa7a63eb0e.png)

The "Codewind for Eclipse" section (rightmost) has an Eclipse Che icon, but refers to the Eclipse IDE which has [a different icon](https://www.google.com/search?client=firefox-b-d&tbm=isch&q=eclipse+ide&chips=q:eclipse+ide,g_1:logo:P6Ip4UKDh9Y%3D&usg=AI4_-kQDpGACRoyRB9u4PCuySs29QLdaxA&sa=X&ved=0ahUKEwjqh_T34aPkAhXig-AKHZHxALsQ4lYIKygA&biw=1680&bih=954&dpr=2). 

The Che icon which is wrongly used there should be used for the "Codewind for Eclipse Che" tile instead.

**Comment by tetchel** [comment]
we should be using the Che icon for `Codewind for Eclipse Che`, not a generic 'cloud' icon

**Comment by sishida** [comment]
@travis1111 Could you please add this logo change? I have the file for the Che logo on hand if you need it. Thank you!

**Comment by travis1111** [comment]
The fix was delivered already.

**Comment by travis1111** [comment]
Sorry the eclipse icon was delivered, I will use the che icon to replace the cloud icon.  I already have the che icon :-)

**Comment by travis1111** [comment]
the fix was delivered

**Comment by sishida** [comment]
Here's a link to the website that shows the fixed images: https://www.eclipse.org/codewind/gettingstarted.html

@tetchel I believe this issue is complete. Could you please close it?

**Comment by tetchel** [comment]
:+1
